name: cal Tranco Rank changes (daily)
on:
  schedule:
    # Run every Monday at 5:00 AM UTC
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  process-rank-data:
    name: Process Rank Data
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Calculate Top Changing Domains (Weekly)
        run: pnpm tsx scripts/topchange-sqlite.ts w
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: top-changing-domains-weekly
          path: data/top_changing_domains.csv
