name: save Tranco Rank daily
on:
  schedule:
    # At 5am every day (for daily analysis)
    - cron: 0 5 * * *
  workflow_dispatch:

jobs:
  process-rank-data:
    name: Process Rank Data
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        analysisType: [daily]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Download and Extract CSV
        if: matrix.analysisType == 'daily' #Only download once a day
        run: |
          wget https://tranco-list.eu/top-1m.csv.zip || exit 1
          unzip top-1m.csv.zip || exit 1
          mv top-1m.csv data/persisted-to-cache/database.csv
          rm top-1m.csv.zip
      - name: Save Rank Data to SQLite
        if: matrix.analysisType == 'daily' # Only save once a day.
        run: pnpm tsx scripts/saveranktocache-sqlite.ts data/persisted-to-cache/database.csv
